// AI-Augmented Stepwise — interactive walkthrough
// Pre-computed numbers are loaded from results.json (generated by running
// ai-stepwise.py locally). The walkthrough animates the project's pipeline
// without re-fitting OLS in the browser.

(function () {
  function renderPrompt(data) {
    document.getElementById("modelTag").textContent = data.model_used;
    document.getElementById("promptText").textContent = data.prompt;
  }

  function renderResponse(data) {
    document.getElementById("responseText").textContent =
      JSON.stringify(data.response, null, 2);
  }

  function renderFeatures(data) {
    const list = document.getElementById("featureList");
    list.innerHTML = data.response.map(f => `
      <div class="feature-item">
        <div class="name">${f.name}</div>
        <div class="formula">${f.formula}</div>
        <div class="rationale">${f.rationale}</div>
      </div>
    `).join("");
  }

  function renderComparison(data) {
    const stats = document.getElementById("rmseStats");
    stats.innerHTML = ["A", "B", "C"].map(key => {
      const m = data.models[key];
      return `
        <div class="demo-stat">
          <div class="label">Model ${key} · ${m.name}</div>
          <div class="value">${m.test_rmse.toFixed(4)}</div>
        </div>`;
    }).join("");

    const bars = document.getElementById("rmseBars");
    const rmses = ["A","B","C"].map(k => data.models[k].test_rmse);
    const maxR = Math.max(...rmses);
    bars.innerHTML = ["A","B","C"].map(key => {
      const m = data.models[key];
      const widthPct = (m.test_rmse / maxR) * 100;
      return `
        <div class="bar-row">
          <div class="label">Model ${key}</div>
          <div class="track"><div class="fill" style="width: ${widthPct.toFixed(1)}%"></div></div>
          <div class="num">${m.test_rmse.toFixed(4)}</div>
        </div>`;
    }).join("");

    document.getElementById("verdict").textContent = data.interpretation.verdict;
  }

  function bindTabs() {
    const tabs = document.querySelectorAll(".storyboard-tabs button");
    const steps = document.querySelectorAll(".storyboard-step");
    tabs.forEach(btn => {
      btn.addEventListener("click", () => {
        tabs.forEach(b => b.classList.remove("active"));
        steps.forEach(s => s.classList.remove("active"));
        btn.classList.add("active");
        document.querySelector(`.storyboard-step[data-step="${btn.dataset.step}"]`).classList.add("active");
      });
    });
  }

  fetch("results.json")
    .then(r => r.json())
    .then(data => {
      renderPrompt(data);
      renderResponse(data);
      renderFeatures(data);
      renderComparison(data);
      bindTabs();
    })
    .catch(err => {
      document.getElementById("promptText").textContent = `Could not load results: ${err.message}`;
    });
})();
